version: "3.8"

services: 

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - public
      - private
    ports:
    - "5173:5173"
  
  backend:
    build: ./backend
    environment:
      - DATABASE_DB=cds_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=cds#1
      - DATABASE_HOST=mariadb
    ports:
      - "1000"
    networks:
      - public
      - private
    depends_on:
      - mariadb

  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - "80:80"
    networks: 
      - public
      - private
    depends_on:
      - phpmyadmin
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=cds#1
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - public
      - private

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=cds#1
      - MYSQL_PASSWORD=cds#1
    ports:
      - "3306:3306"
    volumes: 
      - db:/var/lib/mysql
    networks:
      - public
      - private

networks:
  public:
  private:
volumes:
  db:
