version: "3.8"

services: 
  nodeserver:
    build: .
    ports:
      - "9000:9000"
    networks:
      - private
    depends_on:
      - mariadb
      
  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - "80:80"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: always
  #   environment:
  #     - PMA_HOST: mariadb
  #     - PMA_USER: admin
  #     - PMA_PASSWORD: secret
  #   ports:
  #     - "5050:50"
  #   depends_on:
  #     - mariadb
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_USER=admin
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes: 
      - db:/var/lib/mysql
    networks:
      - private

networks:
  private:
volumes:
  db:
