version: "3.8"

services: 
  nodeserver:
    build: .
    ports:
      - "9000:9000"
    networks:
      - private
    depends_on:
      - mariadb
      
  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - "80:80"
    networks: 
      - private
    depends_on:
      - phpmyadmin
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=admin
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - private

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes: 
      - db:/var/lib/mysql
    networks:
      - private

networks:
  private:
volumes:
  db:
